-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 16:45:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sgbdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgbdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgbdb` DEFAULT CHARACTER SET utf8mb4 ;
USE `sgbdb` ;

-- -----------------------------------------------------
-- Table `sgbdb`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgbdb`.`libro` (
  `idl` INT(11) NOT NULL,
  `nombrel` VARCHAR(255) NULL DEFAULT NULL,
  `autor` VARCHAR(255) NULL DEFAULT NULL,
  `editorial` VARCHAR(255) NULL DEFAULT NULL,
  `generol` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idl`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgbdb`.`ejemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgbdb`.`ejemplar` (
  `idL` INT(11) NOT NULL,
  `idE` INT(11) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idE`),
  INDEX `idL` (`idL` ASC) VISIBLE,
  CONSTRAINT `ejemplar_ibfk_1`
    FOREIGN KEY (`idL`)
    REFERENCES `sgbdb`.`libro` (`idl`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgbdb`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgbdb`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgbdb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgbdb`.`persona` (
  `id` INT(11) NOT NULL,
  `clave` VARCHAR(255) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgbdb`.`multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgbdb`.`multa` (
  `idM` INT(20) UNSIGNED NOT NULL,
  `idP` INT(11) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idM`),
  UNIQUE INDEX `idM` (`idM` ASC) VISIBLE,
  INDEX `FKh7qfq4wh4f3nn9xf890e6o86h` (`idP` ASC) VISIBLE,
  CONSTRAINT `FKh7qfq4wh4f3nn9xf890e6o86h`
    FOREIGN KEY (`idP`)
    REFERENCES `sgbdb`.`persona` (`id`),
  CONSTRAINT `multa_ibfk_1`
    FOREIGN KEY (`idP`)
    REFERENCES `sgbdb`.`persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgbdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgbdb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sgbdb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgbdb`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_rol_unique` (`user_id` ASC, `rol` ASC) VISIBLE,
  CONSTRAINT `fk_rol_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `sgbdb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
